### ISSUE TITLE
pysigma version upkeep

### ISSUE THREAD

**Issue by marcurdy** [AttackIQ/pySigma-backend-microsoft365defender#10]
I want to use this plugin with sigma-cli for conversions of rules.

"sigma plugins install" needs >=0.10.x to install your plugin, but it fails the compatibility check and throws python errors if I ignore checks.

I'm requesting an uplift to 0.10.3 or higher.

**Comment by 0xFustang** [comment]
Same here, I have the same issue.

**Comment by slincoln-aiq** [comment]
Thanks for reporting this! I've increased the supported pySigma version in the `pyproject.toml` in this repository in the most recent version (v0.2.2). 

I also created a pull request for the official plugin directory repository:
https://github.com/SigmaHQ/pySigma-plugin-directory/pull/22

You should be able to install the backend now by skipping compatibility checks (-C). Once the PR is approved, the compatibility check should pass as well. 

Let me know if you are still running into any issues!

**Comment by 0xFustang** [comment]
Thanks! Thanks for making this backend available for the community 😄

**Comment by 0xFustang** [comment]
@slincoln-aiq, I just tried out the latest version and the installation worked fine for me :)

**Comment by slincoln-aiq** [comment]
> @slincoln-aiq, I just tried out the latest version and the installation worked fine for me :)

Awesome, thanks for letting me know! I'll go ahead and close out this issue.
